#default mime types for nanohttpd, use META-INF/mimetypes.properties for user defined mimetypes
css=text/css

htm=text/html
html=text/html

xml=application/xml

md=text/plain
txt=text/plain
asc=text/plain

gif=image/gif
jpg=image/jpeg
jpeg=image/jpeg
png=image/png
svg=image/svg+xml

mp3=audio/mpeg
ogg=audio/ogg

mp4=video/mp4
ogv=video/ogg

pdf=application/pdf

zip=application/zip
